apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-canary
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
      version: canary
  template:
    metadata:
      labels:
        app: demo
        version: canary
    spec:
      containers:
      - name: demo
        image: ghcr.io/fullstackjam/miniproject:9679856e64bca2b75db507a6d0b00e4d6010e0c6
        env:
        - name: VERSION
          value: "canary"
        ports:
        - containerPort: 8080
