apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-canary
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
      version: canary
  template:
    metadata:
      labels:
        app: demo
        version: canary
    spec:
      containers:
      - name: demo
        image: ghcr.io/fullstackjam/miniproject:b900effd189c9e9f55a238a9bf80ef12e05b321b
        env:
        - name: VERSION
          value: "canary"
        ports:
        - containerPort: 8080
