apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-experiment-b
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
      experiment: b
  template:
    metadata:
      labels:
        app: demo
        experiment: b
        version: experiment-b
    spec:
      containers:
      - name: demo
        image: ghcr.io/fullstackjam/miniproject:4fdb863
        imagePullPolicy: Always
        env:
        - name: VERSION
          value: "experiment-b"
        - name: EXPERIMENT
          value: "B"
        ports:
        - containerPort: 8080
